server:
  port: 8010
kafka:
  bootstrap-servers: localhost:9092
  
spring:
  kafka:
    consumer:
      group-id: testEmbeddedKafkaApplication
  cloud:
    stream:
      bindings:
        device_data:
            destination: devicetopic
        heg_topic:
            group: embeddedKafkaApplication
            consumer:
              header-mode: raw
               
              
eureka:
  client:
    enabled: false
